# Generated by Django 5.0.3 on 2024-12-15 11:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name'], 'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='destinationcategory',
            options={'verbose_name': 'Destination Category', 'verbose_name_plural': 'Destination Categories'},
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed description of the destination.'),
        ),
    ]
