# Generated by Django 5.0.3 on 2024-12-15 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_rename_popularity_score_destination_total_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='destination_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Destination ID'),
        ),
    ]
