# Generated by Django 5.0.3 on 2024-12-29 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_destination_destination_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Our Team',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Destination ID'),
        ),
    ]
