# Generated by Django 5.0.3 on 2024-12-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_teammember_alter_destination_destination_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
